### PR TITLE
Simplify by dropping cache_args.

### PR DESCRIPTION
**Pull request by JulienPalard**
Though there were not enough pull request on this repo :p

### CODE REVIEW

**Comment by Seluj78** [comment]
The thing is, if we remove cache args, then some fonctionnality will break because excluded items are in the cache

**Comment by JulienPalard** [comment]
I don't see how it's possible, can you please provide a [minimal reproductible example](https://stackoverflow.com/help/minimal-reproducible-example) of what would break?

**Comment by Seluj78** [comment]
So, the idea is, when you use the cache, the arguments passed in the `exclude` are also not included in the cache, so if you run `potodo --exclude c-api/` then run `potodo` the `c-api` still won't be here. I need to test this, gimme a sec

**Comment by Seluj78** [comment]
Ok well I got lost in my git config but it seems it work !

**Review by Seluj78 — APPROVED** [review]

**Pull request merged**
